---
layout: post
title: 2018-2-2 TIL JAVA Exception(2)
---

#### throw

- 강제로 오류를 발생시키는 throw

```
package Exception;

public class ExceptionExam3 {
    public static void main(String [] args){
        int i = 10;
        int j = 0;
        try {
            int k = divide(i, j);
            System.out.println(k);
        } catch (IllegalArgumentException e){
            System.out.println(e.toString());
        }

    }

    public static int divide(int i, int j) throws IllegalArgumentException {
        if (j == 0){
            throw new IllegalArgumentException("0으로 나눌 수 없습니다.");
        }
        int k = i/j;Bi
        return k;
    }
}

```

#### 사용자 정의 Exception

![](/Users/jimmy/Desktop/exception2.png)

```
## BizException.java

package Exception;

public class BizException extends RuntimeException {
    public BizException(String msg){
        super(msg);
    }

    public BizException(Exception ex){
        super(ex);
    }
}

## BizService.java
package Exception;

public class BizService {
    public void bizMethod(int i) throws BizException {
        System.out.println("비즈니스 메서드 시작");

        if (i < 0)
            throw new BizException("매개변수 i는 0보다 작습니다.");

        System.out.println("비즈니스 메서드 종료");
    }
}

## BizExam.java

package Exception;

public class BizExam {
    public static void main(String [] args){
        BizService biz = new BizService();
        biz.bizMethod(5);
        try{
            biz.bizMethod(-3);
        } catch (Exception e){
            e.printStackTrace();
        }
    }
}

// result

비즈니스 메서드 시작
비즈니스 메서드 종료
비즈니스 메서드 시작
Exception.BizException: 매개변수 i는 0보다 작습니다.
	at Exception.BizService.bizMethod(BizService.java:8)
	at Exception.BizExam.main(BizExam.java:8)

Process finished with exit code 0
```
